FASTER_RCNN_EPOCHS = 100

FASTER_RCNN_BATCH_SIZE = 4

FASTER_RCNN_WORKERS = 8

FASTER_RCNN_LEARNING_RATE = 0.005

FASTER_RCNN_MOMENTUM = 0.9

FASTER_RCNN_WEIGHT_DECAY = 0.0005

FASTER_RCNN_STEP_SIZE = 30

FASTER_RCNN_GAMMA = 0.1